name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main"
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y valgrind g++-14 g++-11 clang-21 clang-tidy-21 ccache

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ccache
        key: ${{ github.workflow }}-ccache-${{ github.sha }}
        restore-keys: |
            ${{ github.workflow }}-ccache-

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cmake -E make_directory build
        cmake -B build \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DBUILD_DOCS=OFF \
          -DUSE_VERILATOR=OFF

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: sudo cmake --install . --config $BUILD_TYPE 2>/dev/null || true

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --verbose
